use std::result::Result;
use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
  Ok(())
}
