use std::error::Error;
use std::result::Result;

fn main() -> Result<(), Box<dyn Error>> {
    Ok(())
}
